// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE0BBTqX56qsD4ceHe3sKBvqjShPrQCBw',
    appId: '1:998036986750:web:932e1ab512d5c77ee2b12f',
    messagingSenderId: '998036986750',
    projectId: 'hackatlon-148ef',
    authDomain: 'hackatlon-148ef.firebaseapp.com',
    storageBucket: 'hackatlon-148ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmyymtdtcmVcMvrYztpAw0ehuj0g7uX8E',
    appId: '1:998036986750:android:e11049be918855e5e2b12f',
    messagingSenderId: '998036986750',
    projectId: 'hackatlon-148ef',
    storageBucket: 'hackatlon-148ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe8kRWX4Gj6ZS4ulXwrwLYdSYEk__0Ygk',
    appId: '1:998036986750:ios:a016b1606b67ac7ae2b12f',
    messagingSenderId: '998036986750',
    projectId: 'hackatlon-148ef',
    storageBucket: 'hackatlon-148ef.appspot.com',
    iosClientId: '998036986750-hp8gp9m91gsc9khqrpbkg6jjdqb14o5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe8kRWX4Gj6ZS4ulXwrwLYdSYEk__0Ygk',
    appId: '1:998036986750:ios:a016b1606b67ac7ae2b12f',
    messagingSenderId: '998036986750',
    projectId: 'hackatlon-148ef',
    storageBucket: 'hackatlon-148ef.appspot.com',
    iosClientId: '998036986750-hp8gp9m91gsc9khqrpbkg6jjdqb14o5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
}
